version: '3.8'

services:
  doculens-backend:
    build:
      context: ../backend
      dockerfile: ../docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - REDIS_URL=redis://redis:6379
    volumes:
      - ../backend/src:/app/src
      - ../backend/uploads:/app/uploads
      - ../backend/logs:/app/logs
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - doculens-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - doculens-network

  # Optional: Redis Commander for Redis management
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - doculens-network

volumes:
  redis_data:

networks:
  doculens-network:
    driver: bridge
